name: projem
description: "THY - Berrin Yilmaz"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.4
  skeletonizer: ^1.4.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/